version: '3.8'

services:
  nutrition-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutrition-calculator-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - nutrition-redis
    networks:
      - nutrition-network
    # Ensures Uvicorn listens on port 8001 for public access
    command: uvicorn app.api:app --host 0.0.0.0 --port 8001 --reload

  nutrition-redis:
    image: redis:alpine
    container_name: nutrition-calculator-redis
    networks:
      - nutrition-network

networks:
  nutrition-network:
    driver: bridge